---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/monitoring/apps
  prune: true
  wait: true
  timeout: 5m0s
  postBuild:
    substitute:
      GW_CLUSTER: ${GW_CLUSTER}
      TEST: ${TEST}
      TEST2: ${TEST2}
      TEST3: ${TEST3}
