apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  prune: false
  postBuild:
    substitute:
      GW_CLUSTER: my-cluster
      TEST: test
      TEST2: abcde
      TEST3: last
      TEST4: text
